### ISSUE TITLE
typos in Software Installation Guide OFS for PCIe Attach (ofs-2024.2-1) and confusion about kernel rebuild requirement for linux-backport driver

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/ofs.github.io#63]
i was reading the Software Installation Guide OFS for PCIe Attach (ofs-2024.2-1) 

https://ofs.github.io/ofs-2024.2-1/hw/common/sw_installation/pcie_attach/sw_install_pcie_attach/#32-building-and-installing-the-ofs-dfl-kernel-drivers-from-source

the step-1:

```
mkdir /home/OFS/
cd /home/OFS/
git init
git clone https://github.com/OFS/linux-dfl-backport
cd /home/OFS/linux-dfl
git checkout tags/intel-1.11.0-2
```

it should be

```
mkdir /home/OFS/
cd /home/OFS/
git init
git clone https://github.com/OFS/linux-dfl-backport
cd /home/OFS/linux-dfl-backport
git checkout tags/intel-1.11.0-2
```

Also when i checkout the this tag, the README.md says:

> Backport version of the linux-dfl (Device Feature List) kernel driver for FPGA devices. This is an out-of-tree driver, designed to be built, packaged, and installed as a stand-alone set of driver modules.
> 
> This is a community project. Individual branches may be owned/maintained by different individuals or organizations to support specific kernel versions.  For example, one branch may be designed specifically to compile against all RHEL 8 kernels, and it may also provide support for building a DKMS package that will build the binary files on the target machine when it is installed. Another branch may build for both RHEL 8 and Ubuntu 22.04.  Others maybe be intended for building binary RPMs for specific kernels.
> 
> Branches are only supported by the individual owners for the purposes for which the branches were created. However, you are free to copy and modify any of the branches within the constraints of the GPL V2 license as described in the included LICENSE file.
> 
> If you would like information on a particular branch, please use the github "Discussions" link to start a conversation. If you can describe your goal, others members should be able to help you determine where to start.

In that case step 3 and on-wards don't apply to `linux-dfl-backport`, because it is standalone DKMS driver, so rebuilding the kernel of RHEL8.8 or RHEL8.10 would not be needed???

**Comment by nathanborak** [comment]
Hello @umairsiddiqui-digitek,

I've replaced references to linux-dfl with linux-dfl-backport in directory navigation steps. 

Regarding:
In that case step 3 and on-wards don't apply to linux-dfl-backport, because it is standalone DKMS driver, so rebuilding the kernel of RHEL8.8 or RHEL8.10 would not be needed???

We provide the steps to build from source in case you wish to make any alterations to the backport repo contents and recompile yourself. You are correct that for most out-of-the-box circumstances, this is not necessary as you can just grab the pre-built file and go from either the github actions or from the OFS release page. I've made it more clear in the steps that this is the case.
